package com.aperam.kryslan.praticaspadrao.BancoDeDados;

import android.content.Context;

import com.aperam.kryslan.praticaspadrao.R;
import com.aperam.kryslan.praticaspadrao.domain.TelaInicialCards;

import java.util.ArrayList;
import java.util.List;


public class BdMainActivity {

    //TABS
    public static String[] GetTabsBd(Context c){
        return new String[]{
                c.getResources().getString(R.string.areaEminente),
                c.getResources().getString(R.string.areasRelacionadas),
                c.getResources().getString(R.string.autor),
                c.getResources().getString(R.string.dataDeVigencia),
                c.getResources().getString(R.string.nivel),
                c.getResources().getString(R.string.processo),
                c.getResources().getString(R.string.restrito),
                c.getResources().getString(R.string.favoritos),
                c.getResources().getString(R.string.historico)};
    }

    //LISTAS
    public static List<TelaInicialCards> GetAreaEmitenteMainActivity() {  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(0, 27);
        String[] foto = GetFotosAreaEminete();
        String[] areaEmitente = GetTitulosAreaEminete();
        String[] grupo = GetGrupo("Área Emitente", 306);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for (int i = 0; i < id.length; i++) {
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    areaEmitente[i % areaEmitente.length],
                    grupo[i % grupo.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetFotosAreaEminete() {
        return new String[]{"https://drive.google.com/uc?id=1Vmq2Fip0oOMOgke-3dAgI5di35xRMJ9D",
                "https://drive.google.com/uc?id=1e5iRGqobvaQLQwvJXsyHlKivBzTKGxDE",
                "https://drive.google.com/uc?id=1ECkekr_tseRV9hqN8ZheXkf6KdEKmZ4R",
                "https://drive.google.com/uc?id=1JpzW9FHqZ8hxncIjV5UQCjuiMo0It8DO",
                "https://drive.google.com/uc?id=1ajHrjGgzBWSZeasmAoz3x2DMpQUdYB3v",
                "https://drive.google.com/uc?id=1FMC1XqTsDl2ZE8EB5B3LXfro7q9jivFp",
                "https://drive.google.com/uc?id=1Lg-PoI0ZWl_VmqvrpvqrhbO1mfBgJIj4",
                "https://drive.google.com/uc?id=1iBpFi9pDiqDP7J3AM2vsPdmvjewB9FAc",
                "https://drive.google.com/uc?id=19JVF6z5DJQQLeFcsJIQn9xZ8B4hfWtCq",
                "https://drive.google.com/uc?id=12GEPI8CG3QzOIlxDaCqEWT4t4PQbAAQg",
                "https://drive.google.com/uc?id=1uNKB0mgig4hzLDDius_9bvvZXW2Z_IUV",
                "https://drive.google.com/uc?id=1EmF52GPiJeQrB9RtZfY_xKvp6Kk4nJ4o",
                "https://drive.google.com/uc?id=1YELai99TmDzf-pmWaj0He5e2EmMktY2j",
                "https://drive.google.com/uc?id=15_D4krC5qoaL5gZXTpzXBahY43LXo-F4",
                "https://drive.google.com/uc?id=1oF7rt_xPXElOdFyt5I6kpMzUNP8o4bGK",
                "https://drive.google.com/uc?id=185TkmfFvLEaRizSvg51fWgVLUL2knkUa",
                "https://drive.google.com/uc?id=1EixpLT90SRtHqO1Ya4a8szZa1Cjrev_E",
                "https://drive.google.com/uc?id=1xlXnPfiyLLUMHoTvqSzMhUOmstqIMRve",
                "https://drive.google.com/uc?id=1tueQb91_k5Q3bHEkalwACZfpqkIVIF95",
                "https://drive.google.com/uc?id=1s9ruZfsjfFxgtHKSuWx6qvP_F-GM8lJe",
                "https://drive.google.com/uc?id=1I64kjuZQP0tvOQFpS-Ek0nv_vso4N8EC",
                "https://drive.google.com/uc?id=11E1UetF4nPm2e9Cea9SYv-pF4TOm8u7j",
                "https://drive.google.com/uc?id=1hCSyOjBk5m-i1UlReYpvVjNq7c5t2Oep",
                "https://drive.google.com/uc?id=13J6ovGF9JM5-a5HsyVHQyjez9wEU8XrK",
                "https://drive.google.com/uc?id=1Sa9WtkOL5TNhx8w15-hBcOwuYYLnt44T",
                "https://drive.google.com/uc?id=1kS4OxjShvwPqpNAOgs1InQBEcLydGCd4",
                "https://drive.google.com/uc?id=1DvL5GJJxPhriljK4C9dEdDkp3HE8lb-C"};
    }
    private static String[] GetTitulosAreaEminete() {
        return new String[]{"Acabamento a Frio de Aços Inoxidáveis",
                "Acabamento a Quente de Aços Inoxidáveis",
                "Acabamento e Reprocessamento de Aços Inoxidáveis",
                "Aciaria",
                "Automação e Otimização de Processos",
                "Centro de Pesquisa",
                "Comunicação Empresarial",
                "Engenharia de Projetos",
                "Gestão Ambiental",
                "Gestão da Excelência Operacional",
                "Gestão da Saúde e Segurança",
                "Gestão de Recursos Humanos",
                "Gestão Financeira",
                "Infraestrutura",
                "Laminação a Frio de Aços Elétricos",
                "Laminação a Frio de Aços Inoxidáveis",
                "Laminação de Tiras a Quente",
                "Logística Integrada",
                "Manutenção Central",
                "Metalurgia",
                "Metalurgia de Aços Elétricos",
                "Metalurgia Integrada",
                "Planejamento Estratégico",
                "Redução",
                "Suprimentos",
                "Tecnologia da Informação",
                "Vendas"};
    }

    public static List<TelaInicialCards> GetAreasRelacionadasMainActivity(){  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(0, 29);
        String[] foto = GetFotosAreasRelacionadas();
        String[] areasRelacionadas = GetTitulosAreasRelacionadas();
        String[] grupo = GetGrupo("Áreas Relacionadas", 29);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for(int i=0; i<id.length; i++){
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    areasRelacionadas[i % areasRelacionadas.length],
                    grupo[i% grupo.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetFotosAreasRelacionadas(){
        return new String[]{"https://drive.google.com/uc?id=1o4Esm_RLPzVqd-jR_s8eEJmEcyx1m3cO",
                "https://drive.google.com/uc?id=19JVF6z5DJQQLeFcsJIQn9xZ8B4hfWtCq",
                "https://drive.google.com/uc?id=1kS4OxjShvwPqpNAOgs1InQBEcLydGCd4",
                "https://drive.google.com/uc?id=11E1UetF4nPm2e9Cea9SYv-pF4TOm8u7j",
                "https://drive.google.com/uc?id=15_D4krC5qoaL5gZXTpzXBahY43LXo-F4",
                "https://drive.google.com/uc?id=1yRxKfdFrQR2G0rMbJPOi0TOtO5u7GCyJ",
                "https://drive.google.com/uc?id=1JpzW9FHqZ8hxncIjV5UQCjuiMo0It8DO",
                "https://drive.google.com/uc?id=1FMC1XqTsDl2ZE8EB5B3LXfro7q9jivFp",
                "https://drive.google.com/uc?id=13J6ovGF9JM5-a5HsyVHQyjez9wEU8XrK",
                "https://drive.google.com/uc?id=1grv5QVOo9Nlga70_x4PMv-ul7E6bLZyw",
                "https://drive.google.com/uc?id=11ZAOFMwRRLMDCQoqVfsEbWUp5jY5mCy8",
                "https://drive.google.com/uc?id=1F_gn6E_DjHqz6MyV2XIxjAjo53Xe0qDx",
                "https://drive.google.com/uc?id=185TkmfFvLEaRizSvg51fWgVLUL2knkUa",
                "https://drive.google.com/uc?id=16anwxKguK8JdhvtHrk2bt_u6HAtkSH7G",
                "https://drive.google.com/uc?id=1oF7rt_xPXElOdFyt5I6kpMzUNP8o4bGK",
                "https://drive.google.com/uc?id=1FJHhcDgzedDIk6KCV0qSRjtGQK3ku5FQ",
                "https://drive.google.com/uc?id=1Sa9WtkOL5TNhx8w15-hBcOwuYYLnt44T",
                "https://drive.google.com/uc?id=1uNKB0mgig4hzLDDius_9bvvZXW2Z_IUV",
                "https://drive.google.com/uc?id=12GEPI8CG3QzOIlxDaCqEWT4t4PQbAAQg",
                "https://drive.google.com/uc?id=1yoIUz1qmJF89hclVy4MCy2MjLoajzx10",
                "https://drive.google.com/uc?id=1xlXnPfiyLLUMHoTvqSzMhUOmstqIMRve",
                "https://drive.google.com/uc?id=1YELai99TmDzf-pmWaj0He5e2EmMktY2j",
                "https://drive.google.com/uc?id=1DvL5GJJxPhriljK4C9dEdDkp3HE8lb-C",
                "https://drive.google.com/uc?id=1ghzl5M1Iv4S-EUVvy2ifi1Au3MmwI29e",
                "https://drive.google.com/uc?id=1hCSyOjBk5m-i1UlReYpvVjNq7c5t2Oep",
                "https://drive.google.com/uc?id=1tueQb91_k5Q3bHEkalwACZfpqkIVIF95",
                "https://drive.google.com/uc?id=1Lg-PoI0ZWl_VmqvrpvqrhbO1mfBgJIj4",
                "https://drive.google.com/uc?id=1Vmq2Fip0oOMOgke-3dAgI5di35xRMJ9D",
                "https://drive.google.com/uc?id=1ajHrjGgzBWSZeasmAoz3x2DMpQUdYB3v"};
    }
    private static String[] GetTitulosAreasRelacionadas(){
        return new String[]{"Núcleo 01 - Arquivo Central",
                "Núcleo 02 - Gestão Ambiental",
                "Núcleo 03 - Tecnologia da Informação",
                "Núcleo 04 - Metalurgia Integrada",
                "Núcleo 05 - Infraestrutura",
                "Núcleo 07 - Fundação Aperam Acesita",
                "Núcleo 09 - Aciaria",
                "Núcleo 10 - Centro de Pesquisa",
                "Núcleo 11 - Redução",
                "Núcleo 12 - Laboratório Químico",
                "Núcleo 13 - Manutenção da Aciaria",
                "Núcleo 15 - Metrologia",
                "Núcleo 17 - Laminação a Frio de Inoxidáveis",
                "Núcleo 19 - Laminação a Quente",
                "Núcleo 20 - Laminação a Frio de Aços Elétricos",
                "Núcleo 22 - Relações Trabalhistas",
                "Núcleo 23 - Suprimentos",
                "Núcleo 24 - Gestão da Saúde e Segurança",
                "Núcleo 25 - Gestão da Excelência Operacional",
                "Núcleo 26 - Desenvolvimento e Treinamento",
                "Núcleo 27 - Logística Integrada",
                "Núcleo 28 - Vendas",
                "Núcleo 31 - Gestão Financeira",
                "Núcleo 32 - Engenharia de Projetos",
                "Núcleo 37 - Planejamento Estratégico",
                "Núcleo 38 - Manutenção Central",
                "Núcleo 39 - Comunicação Empresarial",
                "Núcleo 40 - Acabamento a Frio de Aços Inoxidáveis",
                "Núcleo 43 - Automação e Otimização de Processos"};
    }

    public static List<TelaInicialCards> GetAutorMainActivity() {  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(1, 306);  //Futuramente criar clase para cada um em domain.
        String[] foto = GetVoidString(306);
        String[] tutulo = GetTituloAutor();
        String[] grupo = GetGrupo("Autor", 306);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for (int i = 0; i < id.length; i++) {
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    tutulo[i % tutulo.length],
                    grupo[i % grupo.length]);
            //link[i % link.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetTituloAutor(){
        return new String[]{"ABNER LUCIO F DUTRA",
                "Adão Cordeiro de Azevedo",
                "ADILSON A GONCALVES",
                "ADIR SOARES DE M JUNIOR",
                "ADJACIR DE SOUSA",
                "Administrador Docnix",
                "ADRIANO HENRIQUE SILVA",
                "Adriano Oliveira Vago",
                "AGNALDO PAULO DA SILVA",
                "Agnaldo Pinto Fiuza",
                "AGNALDO SILVA CARVALHO",
                "Ailton Costa de Azevedo",
                "AILTON RODRIGUES DO PRADO",
                "ALCY DIAS RODRIGUES",
                "ALESCIANO G SILVA PEREIRA",
                "ALEXANDRE VELOSO VIEIRA",
                "ALINE SOARES N ALVARENGA",
                "Altieres Fernando Gomes Carneiro",
                "AMARILDO FERREIRA DOS SANTOS#181940",
                "ANDERSON JONNE SANT ANA",
                "Andre Luiz Pires de Figueiredo",
                "Angelica Fabiana Batista P de",
                "Angelo Antonio Gonçalves Coelho",
                "ANGELO FERREIRA COSTA",
                "ANGELO ROSA DA SILVA",
                "ANTONIO CARLOS DE ASSIS",
                "ANTONY WILLIAM DE ALMEIDA",
                "ARISIO DE ABREU BARBOSA",
                "ARLEN CARNEIRO DE ARAUJO",
                "BRUNO CORDEIRO COSTA",
                "BRUNO DE ALMEIDA MIRANDA",
                "CAIO DE PAULA CAMARGO PISANO",
                "CARINE DE OLIVEIRA MAIA",
                "CARLOS A A DE OLIVEIRA",
                "CARLOS ALBERTO MOURAO",
                "CARLOS HENRIQUE DE CASTRO",
                "Carlos Oliveira Costa",
                "CELIA MARIA S RODRIGUES",
                "CHARLES SILVA MAGALHAES",
                "CHARLSTON N RIBEIRO",
                "CLAUDIANO Z FONTOURA",
                "Claudilene Aparecida Alves Pena",
                "CLAUDIMAR P DOS SANTOS",
                "CLAUDIO M DE ALCANTARA",
                "Claudio Roberto de Paula",
                "CLAUDIO SILVA MIRANDA",
                "CLAUDIO TEIXEIRA GOMES",
                "Cleberson Marcelo dos Santos",
                "CLEIDE C DA S FAUSTINI",
                "CLEONICE M ALVES FREITAS",
                "CLINGER FELIX SANTIAGO",
                "CRISTIAN C DE FREITAS",
                "CRISTINA BORGES P M ALTO",
                "CYNTIA RENATA VALERIANO DE OLIVEIRA",
                "DALTON HERINGER DE SOUZA",
                "Darleny Fernandes Vieira",
                "DENISE A BARCELOS ASSIS",
                "DILSON P DE MELO",
                "DIOGO FERREIRA DE CASTRO",
                "DIONATAN M A MARINHO",
                "DOUGLAS FERREIRA DE SOUSA",
                "EDILSON MARCIO NOGUEIRA",
                "EDILSON S CAVALIERI",
                "EDMAR G PATROCINIO",
                "EDNA LEITE SILVA",
                "EDNEI ARAUJO CLARA",
                "EDSON AMORIM",
                "EDSON JOSE ALVES",
                "EDSON MOURA OLIVEIRA",
                "EDUARDO LUIZ G TEIXEIRA",
                "EDUARDO MILAGRES DA SILVA",
                "EDVAL SOARES DE SOUZA",
                "ELIAS CARLOS LOPES",
                "ELISA DAS GRACAS S LEVI",
                "Elvio Goncalves do Nascimento",
                "ELYSE PENHA P S E SILVA",
                "EMILIANA C M ARTHUSO",
                "ENILBER LUCAS SILVA",
                "ERICH FABIANY SANTOS",
                "ERLI APARECIDO DE PAULA JUNIOR",
                "ERMELINO VIEIRA COURA",
                "EURONIDES V P FILHO",
                "Ezio Vinicius Santos",
                "FABIANO SOUSA ARAUJO¹",
                "FABIO DE ASSIS VALENTE",
                "Fabio Gomes Pacheco",
                "FABIO GOMES PACHECO#365458",
                "FABRICIO L DE ALCANTARA",
                "Fausto Figueiredo Gomes",
                "FELIPE GRATIVOL LIMA",
                "FELLIPE H BRITO CARVALHO",
                "FERNANDA DE SA OLIVEIRA LIZARDO¹",
                "FERNANDO ALVES ALVARENGA",
                "FILEMON SILVA MENDES",
                "FILIPE SOARES PONTES",
                "FLAMARION ANICIO BATISTA",
                "Flavia Adalgisa Magalhaes Santos",
                "FLAVIO ANTONIO RIBEIRO",
                "FLAVIO APARECIDO LIMA DE ANDRADE",
                "FLAVIO BARCELOS MORAIS",
                "FLAVIO DA SILVA",
                "FRANCISCO DUARTE FERREIRA",
                "FRANCISCO GONCALVES LIMA",
                "GABRIEL RODRIGUES LUZIA",
                "GAVYLAM SILVA DE ALMEIDA",
                "Geirson Neves Gandra",
                "GEOVANY SANTIAGO SOARES",
                "Geraldo aparecido leandro",
                "GERALDO APARECIDO S SOUSA",
                "GERALDO DE ASSIS SILVA",
                "GERALDO M DA SILVEIRA",
                "GERALDO MARCOS DE SOUZA",
                "GIL NEY CHAVES ULHOA",
                "GILBERTH B DE O ALVES",
                "GILBERTO DE ALMEIDA",
                "GILCESAR G S N DE AVILA",
                "GILSON JUSTO REIS",
                "GLAUBER F BATISTA",
                "GLAUTIERE PAIVA GOMES",
                "GUILHERME F BARBOSA COURA",
                "HELITON MARTINS REIS",
                "HELTON ALMEIDA NEVES",
                "HERMAN SAVIO DE SOUZA",
                "HUGLESLEI V M SILVA",
                "HUMBERTO DE O ARAUJO",
                "HUMBERTO SOUSA BARCELOS",
                "IRIMAR NOVAES SILVA#360940",
                "IVANILSON BISPO DE ALMEIDA",
                "IVONILSON F DE ALMEIDA",
                "JANE DE L FERRAZ BARRILAO",
                "JANEIR RIBEIRO DUTRA",
                "JEAN ALVES DE SOUZA",
                "JEANDERSON E MUNIZ SILVA",
                "JENNER COSTA FERREIRA",
                "Jessica Aparecida Cordeiro",
                "JOAO BOSCO F PACIFICO",
                "JOAO GERALDO ALVES",
                "JOAO KENEDE MAGALHAES",
                "Joao Paulo Gomes Moreira",
                "JOAQUIM GOMES DE SOUZA",
                "JOSE BENIGNO DE ASSIS",
                "JOSE CARLOS MARTINS SILVA",
                "JOSE CARLOS ROSA DA SILVA",
                "JOSE GERALDO DE C AMERICO",
                "JOSE GERALDO DOS SANTOS",
                "Jose Luiz de Matos",
                "JOSE R DE OLIVEIRA",
                "JOSE RENATO SILVA NUNES",
                "JOSE RIBEIRO DE A FILHO",
                "JOSE ROBERTO DA CRUZ",
                "JOSE ROBERTO SIMAO",
                "JOSE ROMARIO DE F MOTA",
                "Josimar Mendes Araujo",
                "JOYCE FRANCELE ROCHA GOMES",
                "JULIO CESAR C CALDEIRA",
                "JUSAEL DE ALMEIDA",
                "KEYFERSON G FERREIRA",
                "KLEBER M DE OLIVEIRA",
                "Kleolvane Carlos Figueiredo de Paula",
                "Leila Miriam Oliveira",
                "LEONARDO A FERNANDES",
                "LEONARDO DE A HORACIO",
                "LEONARDO DE A RIBEIRO",
                "LINCOLN DOS S RODRIGUES",
                "LUCELIO MIRANDA",
                "LUCIANA NASCIMENTO OLIVEIRA FAVARATO",
                "Luciano Fernandes Viana",
                "LUCIANO M DA SILVA",
                "Lucimar Aparecida dos Reis Gomes#20160801",
                "Lucio Asai Bailo",
                "LUIS CARLOS ASSUNCAO",
                "LUIS CLAUDIO B TORRES",
                "LUIZ ANDRE DE OLIVEIRA¹",
                "LUIZ CLAUDIO ANDRE PINTO",
                "MAGDA REGINA S PLAIS",
                "MAGNO GOMES FRADE",
                "MARCELO FERREIRA COSTA",
                "MARCELO LOPES M BORGES",
                "MARCELO SEIXAS VIEIRA",
                "MARCELO SOUZA PEREIRA",
                "MARCIA A MIRANDA DE ASSIS",
                "MARCIO A G FERNANDES",
                "MARCIO FERREIRA RODRIGUES",
                "MARCO AURELIO DE A NEIVA",
                "MARCO SERGIO C DO ROSARIO",
                "MARCOS AURELIO S PEDROSA",
                "MARCUS HAROLDO R FERREIRA",
                "MARCUS MICHEL ELIAS",
                "MARDLIRIO JOSE MARTINS",
                "MARIA DE J DE P FREITAS",
                "Maria do Socorro de Souza Lima",
                "MARIA REGINA B MENDES",
                "MARIO SERGIO MOURAO",
                "MARLI GERONIMA",
                "MARLON BUENO FELIX",
                "MAURICIO CESAR PEREIRA RODRIGUES",
                "Michele Cristina Marques Rosa",
                "MICHELLA F BEZERRA BARONY",
                "Milane Mendes de Macedo",
                "MILTON ASSIS DA SILVA",
                "Milton Pereira dos Santos Junior",
                "MOISES J L DA SILVA",
                "NAGYLA FRIGULHA DE M LIMA",
                "NELSON LUCAS ALVES JUNIOR",
                "NEY SOUSA MOREIRA",
                "NILDOMAR SOARES FERREIRA",
                "NILTON CESAR LOURENCO",
                "NIVALDO FERREIRA SILVA",
                "Nivaldo Santos da Silva",
                "Nucleo Acabamento de Laminados a Quente",
                "Nucleo Acabamento e Servicos em Inox",
                "Nucleo Centro de Pesquisa",
                "Nucleo da Engenharia de Manutencao",
                "Nucleo Gestao Ambiental",
                "Nucleo Gestao Estrategica",
                "Nucleo Laminacao de Inox",
                "Nucleo Laminacao de Siliciosos",
                "Nucleo Laminacao Tiras a Quente",
                "Nucleo Metrologia",
                "Nucleo Posto Medico",
                "Nucleo Reducao",
                "Nucleo Transporte Externo",
                "Nucleo Utilidades",
                "ORISRAK ALVES DORNELAS",
                "Osvaldo Pires Ferreira",
                "OTAVIO A DA C TEIXEIRA",
                "PATRICIA ZELIA DE ASSIS",
                "PATRICK QUINTAO VIEIRA",
                "Paulino Cordeiro de Oliveira",
                "PAULO CESAR GONCALVES",
                "PAULO H DOS SANTOS",
                "PAULO HENRIQUE DE OLIVEIRA MAIA#197370",
                "PAULO JOSE DE SOUZA",
                "PAULO JUNIO DE S BARBOSA",
                "PAULO RICARDO MUSSI OLIVEIRA",
                "PEDRO GONCALVES DOS REIS",
                "PEDRO HENRIQUE B SOUZA",
                "Polibio Martins Nogueira",
                "RAFAEL LOPES F PENEDO",
                "Rafaella Pereira",
                "Raquel Alves Correia",
                "RAQUEL MENDONCA DE FARIA",
                "RAVENY CRISTINY ASSIS FRANCISQUINI",
                "RAYLANDER ROCHA PESSOA",
                "Regilsllainy Cobucci Pena",
                "REGINA CELIA DE MELO",
                "REINALDO DE OLIVEIRA CRUZ",
                "REINALDO O G JUNIOR",
                "REINALDO SANTOS SILVA",
                "REINALDO SILVANO SANTOS#235641",
                "RENATO A DE A SANTANA",
                "Ricardo Antonio Ferreira de Oliveira",
                "RICARDO JOSE G COSTA",
                "RICHARD ANDRE PERDIGAO",
                "RIVA ULTIMO DE C MOREIRA",
                "ROBERTA SILVA NUNES",
                "ROBERTO JUNIOR G LEITE",
                "ROBERTO ROSA LUPPI",
                "ROBSON DE SOUZA BARCELOS",
                "ROBSON GUIMARAES LOPES",
                "ROBSON MARTINS",
                "ROBSON WANDER SILVA SOUZA",
                "Rodolfo Manoel Lemes da Costa",
                "RODRIGO BARONY BRUZI",
                "ROGERIO RUIZ SANCHEZ",
                "Romario Emiliano Barbosa Olimpo",
                "ROMILSON FREITAS SOUZA",
                "RONALDO C DE OLIVEIRA",
                "Ronielly Lemos.#20160827",
                "RONILDO RODRIGUES SOUSA",
                "RONILDSON G MONTEIRO",
                "RONNE FERREIRA PIRES",
                "RUBENS DA SILVA MOURA",
                "RUBENS GOMES PESSOA",
                "SANDEY NOVY ARAUJO ROCHA",
                "SANDRO M SOUSA FELIX",
                "SANNCLEY AUGUSTO RUFINO",
                "SERGIO BRUM LUGAO",
                "SERGIO MIRANDA DA SILVA",
                "Sergio Ricardo Martins",
                "Sergio Silveira de Vasconcellos Aprigio Junior",
                "SHEYLLA LIMA SOUZA",
                "SHIRLLENY F DE LIMA SOUZA",
                "SIDLEY RAMOS BARCELOS",
                "Silas Roberto Machado Vilela",
                "SILVERIO SANTANA FONTES",
                "SILVIMAR GONCALVES CAMPOS",
                "SOLANGE VALENTIM PEREIRA",
                "STELO ALEIXO DE C FILHO",
                "TALES WALLACE SOUZA",
                "TANIA M A DOS S G PESSOA",
                "TEOFILO M DE S SANTOS",
                "THAIS APARECIDA CASTRO DA SILVA",
                "THIAGO V DE O BARBOSA",
                "TIAGO BATISTA DOS SANTOS",
                "TIAGO M DE O EGIDIO",
                "Tony Terra Beraldo",
                "VAGNER M DE CARVALHO",
                "VALQUIRIA CARVALHO ARDUINI",
                "Vanessa Marques da Silva",
                "VERA LUCIA GASQUEL COELHO#386772",
                "VICENTE SANTALUCIA",
                "VICTOR M C DE OLIVEIRA",
                "VINICIUS M DE CARVALHO",
                "VIVALDO GERALDO DINIZ",
                "WALDER BENVINDO OLIVEIRA CARVALHO",
                "Waldmir de Assis Castro",
                "WALTON FERNANDES DA SILVA",
                "WANDERLEY V DE FARIA",
                "WANDERNY MENDES RIBEIRO",
                "WANDERSON SILVA MARQUES",
                "WELINGTON MADUREIRA SILVA",
                "Wellisson Ferreira",
                "WESLEY DE CARVALHO SILVA",
                "WILD GONCALVES DE SOUZA",
                "WILLIAM CLAYTON A ALMEIDA",
                "WILSON PEREIRA"};
    }

    public static List<TelaInicialCards> GetDataDeVigenciaMainActivity() {  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(2, 12);  //Futuramente criar clase para cada um em domain.
        String[] foto = GetVoidString(12);
        String[] titulo = GetTituloDataDeVigencia();
        String[] grupo = GetGrupo("Data de Vigência", 12);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for (int i = 0; i < id.length; i++) {
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    titulo[i % titulo.length],
                    grupo[i % grupo.length]);
            //link[i % link.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetTituloDataDeVigencia(){
        return new String[]{
                "2017",
                "2016",
                "2015",
                "2014",
                "2013",
                "2012",
                "2011",
                "2010",
                "2009",
                "2008",
                "2007",
                "2006",
                "2018"};
    }

    public static List<TelaInicialCards> GetNivelMainActivity() {  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(0,3);  //Futuramente criar clase para cada um em domain.
        String[] foto = GetFotoNivel();
        String[] titulo = GetTituloNivel();
        String[] grupo = GetGrupo("Nível", 306);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for (int i = 0; i < id.length; i++) {
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    titulo[i % titulo.length],
                    grupo[i % grupo.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetTituloNivel(){
        return new String[]{"Corporativo", "Operacional", "Técnico"};
    }
    private static String[] GetFotoNivel(){
        return new String []{"https://drive.google.com/uc?id=1KXOnNwnZHhsLLEhDSbHT7qRrcw1BrkqD",
                "https://drive.google.com/uc?id=1Y3_kD2-WeHdb0iubxB4XkxZhacTQ7x0S",
                "https://drive.google.com/uc?id=1subUEz1ecv08QUNAMzAxmg13ba2SFcM3"};
    }

    public static List<TelaInicialCards> GetProcessoMainActivity() {  //PEGAR DEPOIS NO DOCNIX.
        int[] id = GetTipo(3, 304);  //Futuramente criar clase para cada um em domain.
        String[] foto = GetVoidString(304);
        String[] titulo = GetTituloProcesso();
        String[] grupo = GetGrupo("Processo", 306);
        List<TelaInicialCards> listAux = new ArrayList<>();

        for (int i = 0; i < id.length; i++) {
            TelaInicialCards p = new TelaInicialCards(
                    id[i % id.length],
                    foto[i % foto.length],
                    titulo[i % titulo.length],
                    grupo[i % grupo.length]);
            //link[i % link.length]);
            listAux.add(p);
        }
        return listAux;
    }
    private static String[] GetTituloProcesso(){
        return new String[]{" Acabamento Superficial",
                "Aceiros",
                "Ações Corretivas e Preventivas",
                "Administração de Pessoal",
                "Adquirir Produtos e Serviços",
                "AF1-Carregamento",
                "AF1-Check-list",
                "AF1-Cowpers",
                "AF1-Lingotamento de Gusa",
                "AF1-Processo",
                "AF1-Risco Operacional",
                "AF1-Soprador",
                "AF1-Transporte Carro Torpedo",
                "AF1-Tratamento de Gás",
                "AF1-Vazamento",
                "AF2-Carregamento",
                "AF2-Check-list",
                "AF2-Cowpers",
                "AF2-Processo",
                "AF2-Refrigeração",
                "AF2-Refrigeração_Inativo",
                "AF2-Risco Operacional",
                "AF2-Soprador",
                "AF2-Tratamento de Gás",
                "AF2-Vazamento",
                "Altos-Fornos",
                "Ambiência",
                "Análise da Capacidade de Produção",
                "Análise Físico e Química",
                "Análise Físico e Química de Meio Ambiente",
                "Análise Química Instrumental",
                "Análise Química por Via Úmida",
                "Aquisição",
                "Aquisição/Lançamento Cabos Alta Tensão",
                "Arquivo Central",
                "Aspectos Ambientais",
                "Atendimento a Legislação",
                "Auditorias Normativas",
                "Automação",
                "Avaliação do Desempenho",
                "Baldeio",
                "Biblioteca",
                "Cadeia de Custódia",
                "Capacidade Técnica dos Equipamentos",
                "Carbonização",
                "Carregamento",
                "Carregamento de Forno",
                "Casa da Sombra",
                "Casa de Vegetação",
                "Cercas",
                "CL1-Revestimento Carlite e Aplainamento Térmico",
                "Combate a Pragas e Doenças",
                "Comunicação Empresarial",
                "Comunicação Empresarial",
                "Condução de Brotação",
                "Confirmação Metrológica",
                "Conservação da Biodiversidade",
                "Conservação do Solo",
                "Consignação para Intervenção em Equipamentos",
                "Controle de Dispositivos de Medição",
                "Controle de Entrada de Madeira",
                "Controle de Insumos Críticos",
                "Controle de Não Conformidades",
                "Controle de Processo",
                "Controle de Produto Não Conforme",
                "Controle, Qualidade e Biorredutor",
                "Correções e Melhorias GST",
                "Corte a Guilhotina",
                "Corte a Plasma",
                "Corte Longitudinal",
                "Corte Longitudinal e Embalagem",
                "Corte Transversal",
                "Crescimento Seleção Rustificação",
                "Cubagem Rigorosa",
                "DC1-Descarbonetação de GO/GNO",
                "Decapagem Química",
                "Depósito de Bobinas e Chapas - DBQ",
                "Derrubada",
                "Descarga",
                "Descarga de Forno",
                "Desenvolvimento de Projetos",
                "Devolução de Produtos",
                "Distribuição de Fluidos",
                "Distribuição de GAF",
                "EBs-Esmerilhamento de Bobinas",
                "EB1-Esmerilhamento de Bobinas",
                "EB2-Esmerilhamento de Bobinas",
                "Embalagem de Produto",
                "EM2-Embalagem de Bobinas - GO/GNO",
                "Esmerilhamento de Placas",
                "Especificação de Aços Elétricos",
                "Especificação de Insumos Críticos",
                "Especificação de Matéria-Prima",
                "Especificação de produtos",
                "Especificação de Produtos Inoxidáveis",
                "Estocagem de Carvão",
                "Estradas",
                "Expedição",
                "Expedição de Carvão",
                "Expedição de Produto",
                "Fertilização (Nutrição)",
                "Fundação Aperam Acesita",
                "Geração de Vapor",
                "Gerenciamento da Rotina",
                "Gerenciamento de Projetos",
                "Gerenciamento de Resíduos",
                "Gerenciamento de Risco Operacional",
                "Gerenciamento do Fluxo de Sucata",
                "Gerir Matérias-Primas e Produtos Industriais",
                "Gerir Processos Internos e Informações de Suprimentos",
                "Gerir Relacionamento com Fornecedores",
                "Gestão Apoio Técnico",
                "Gestão da Excelência Operacional",
                "Gestão de Bens Móveis",
                "Gestão de Ensaios e Testes",
                "Gestão de Infraestrutura de TI",
                "Gestão de Riscos GST",
                "Gestão de Segurança da Informação",
                "Gestão de Sistema de Informação",
                "Gestão de Sobras em Industrializador",
                "GT-Processo",
                "GT-Refratário",
                "Higiene Ocupacional",
                "ICP-Ação Preventiva no Processo",
                "ICP-Check-list",
                "ICP-Estocagem",
                "ICP-Processo",
                "ICP-Recebimento de Matérias Primas",
                "ICP-Sistema Combate Incêndio e Explosão",
                "ICP-Sistema de Injeção e Transporte",
                "ICP-Sistema de Moagem e Secagem",
                "Identificação e Preservação do Produto",
                "Identificação e Rastreabilidade",
                "Industrialização de Aços Elétricos",
                "Injeção de Carvão Pulverizado",
                "Inspeção de Aços Elétricos",
                "Inspeção de Cintagem",
                "Inspeção de Produtos",
                "Inspeção de Produtos Inoxidáveis",
                "Inventário Físico",
                "Inventário Florestal Contínuo",
                "Jardim Clonal",
                "Laboratório Corrosão e Superfície",
                "Laboratório de Eletrônica",
                "Laboratório de Estampagem",
                "Laboratorio de Métodos Físicos",
                "Laboratório de Revestimento",
                "Laboratório de Soldagem e Torção",
                "Laboratório Integrado",
                "Laboratórios de Ensaios Magnéticos",
                "Laboratórios de Ensaios Mecânicos",
                "Laboratórios de Ensaios Termomecânicos",
                "Laminação de Chapas e Bobinas",
                "LBs-Laminação de Bobinas",
                "LB1-Laminação de Bobinas",
                "LB2-Laminação de Bobinas",
                "LB3-Laminação de Bobinas",
                "LB4-Laminação de Bobinas",
                "LE1-Laminação de Encruamento",
                "LFI -Armazenamento, Preservação e Manuzeio",
                "LFI-Armazenamento, Preservação e Manuzeio",
                "LFI-Geral",
                "LFI-Insumos",
                "Logística",
                "Logística de Transporte",
                "Manobra Elétrica",
                "Manutenção",
                "Manutenção Corretiva",
                "Manutenção da Aciaria",
                "Manutenção da LTQ",
                "Manutenção de Campo",
                "Manutenção de Forno",
                "Manutenção de Infra-Estrutura",
                "Manutenção de 90 dias",
                "Manutenção Elétrica",
                "Manutenção em Instrumentação",
                "Manutenção em Sistemas de Automação",
                "Manutenção Mecânica",
                "Manutenção Preventiva",
                "Manutenção Refratária",
                "Medição e Monitoramento de Desempenho GST",
                "Medição e Monitoramento de Processo",
                "Medição e Monitoramento do Produto",
                "Medicina do Trabalho",
                "Medidas de Controle GST",
                "Melhoramento",
                "Melhorias",
                "Metalurgia do Carbono",
                "Metrologia",
                "Monitoramento Ambiental",
                "Mostruários de Acabamento Superficial",
                "Obra Civil",
                "Ocorrência de Sinistros AT",
                "Oficina de Manutenção de Conjuntos",
                "Organização e Limpeza",
                "Pátio-Abastecimento",
                "Pátio-Beneficiamento",
                "Pátio-Escoamento",
                "Pátio-Estocagem",
                "Pátio-Inventário",
                "Pátio-Movimentação de Matérias-Primas",
                "Pátio-Recebimento",
                "Pátio-Risco Operacional",
                "PBs-Preparação de Bobinas",
                "PB1-Preparação de Bobinas",
                "PB2-Preparação de Bobinas",
                "PB3-Preparação de Bobinas",
                "Planejamento de Recursos Humanos",
                "Planejamento de Vendas",
                "Planejamento do Negócio",
                "Planejamento e Programação",
                "Planejamento, Programação e Controle da Produção",
                "Plano de Contingência",
                "Plano de Controle",
                "Plantio",
                "Preparação de Cilindros",
                "Preparação e Controle de Panelas de Lingotamento",
                "Preparação e Manutenção Refratária de Distribuidores",
                "Preparação e Respostas à Emergências",
                "Preparo do Solo",
                "Preservação de Produtos",
                "Pré-Tratamento de Gusa Via PTG",
                "Processos Administrativos",
                "Processos Relacionados a Clientes",
                "Produção de Aço Via AOD-L",
                "Produção de Aço Via MRP-L",
                "Produção de FeCr Via FER",
                "Produção de Placas de Aço Via Lingotamento Contínuo",
                "Produção de Pré-Metal Via FEAs",
                "Programas e Projetos de Melhoria",
                "Projeto e Desenvolvimento",
                "Projetos de Pesquisa",
                "Provisão de Recursos",
                "Qualidade da Água",
                "RBs-Recozimento e Decapagem de Bobinas",
                "RB1-Recozimento e Decapagem de Bobinas",
                "RB2-Recozimento e Decapagem de Bobinas",
                "RB3-Recozimento e Decapagem de Bobinas",
                "RB4-Recozimento e Decapagem de Bobinas",
                "RCs-Recozimento de Bobinas em Caixa",
                "RC2-Recozimento em Caixa de GO",
                "RC3-Recozimento de Bobinas em Caixa",
                "Realização Ensaios e Testes Aços Elétricos e Carbono",
                "Reaquecimento de Placas",
                "Receber, Armazenar e Abastecer Matérias Primas e Produtos Industriais",
                "Receber, Armazenar e Entregar Materiais",
                "Recebimento de Produto",
                "Recrutamento e Seleção",
                "Recuperação de Produto",
                "Refino de Aço Via Forno Panela",
                "Refino de Aço Via VOD1",
                "Refino de Aço Via VOD2",
                "Refrigeração Água Recirculada",
                "Regeneração de Ácido",
                "Relações com as Comunidades",
                "Relações de Trabalho",
                "Relações Trabalhistas",
                "Requisitos de Documentação",
                "Requisitos de Fornecedores",
                "Requisitos de Materiais",
                "Requisitos de Serviços",
                "Requisitos Gerais",
                "Requisitos Gerais - LTQ",
                "Requisitos Legais",
                "Resfriamento de Forno",
                "Responsabilidade da Direção",
                "RP1-Reparação de Bobinas de Aços Elétricos",
                "RTs-Retíficas de Cilindros",
                "RT1-Retífica de Cilindros",
                "RT2-Retífica de Cilindros",
                "RT3-Retífica de Cilindros",
                "RT4-Retífica de Cilindros",
                "RT5-Retífica de Cilindros",
                "RT6-Retífica de Cilindros",
                "RT7-Retífica de Cilindros",
                "RT8-Retífica de Cilindros",
                "Satisfação de Clientes",
                "Saúde Ocupacional",
                "Segurança do Trabalho",
                "Segurança Patrimonial",
                "Segurança Patrimonial - Bombeiros",
                "Segurança Patrimonial - Fiscalização",
                "Segurança Patrimonial - Suporte Operacional",
                "Serviços Administrativos",
                "Silvicultura",
                "Sucatamento de Produto",
                "Suprimentos para Produção",
                "TD1 e TD2 - Recozimento e Descarbonetação de GNO",
                "TL-Corte Longitudinal",
                "TL2-Corte Longitudinal",
                "TL3-Corte Longitudinal",
                "TL7-Corte Longitudinal",
                "Traçamento",
                "Transporte",
                "Transporte Interno Ferroviário",
                "Tratamento de Insumos e Ligas",
                "Tratamento de Utilidades Não-Conformes",
                "Tratamento Térmico",
                "Tratos Culturais",
                "Treinamento",
                "Treinamento e Desenvolvimento",
                "TS Metalurgia Secundária",
                "Uso de EPIs nas Atividades de Distribuição de Energia Elétrica",
                "Documentos Não Categorizados  "};
    }

    //UTILS
    private static int[] GetTipo(int valor, int qtd){
        int[] qtdVoid = new int[qtd];
        for (int i = 0; i < qtd; i++) {
            qtdVoid[i] = valor;
        }
        return qtdVoid;
    }
    private static String[] GetGrupo(String grupo, int qtdId){
        String[] qtd = new String[qtdId];
        for (int i = 0; i < qtdId; i++) {
            qtd[i] = grupo;
        }
        return qtd;
    }
    private static String[] GetVoidString(int qtdId){
        String[] qtd = new String[qtdId];
        for (int i = 0; i < qtdId; i++) {
            qtd[i] = "" + i;
        }
        return qtd;
    }
}
